[package]
name = "rust_reddit_user_scraper"
version = "0.1.0"
authors = ["Calum Forster <calumforster@live.co.uk>"]

[dependencies]
dotenv = "0.10.1"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
tokio-core = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
